name: viz
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - seaborn
  - scikit-learn
  - scipy
  - matplotlib
  - jupyterlab
  - ipykernel
  - bokeh
  - altair
